---
name: Main
on:
  push:
    branches:
      - 'dev'

  workflow_dispatch:

jobs:
  push-latest-image:
    name: Push the latest image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ghcr.io/JacekZubielik/dummy-metrics:latest .
      - name: Login to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Push image
        run: docker push ghcr.io/JacekZubielik/dummy-metrics:latest
